XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
XXXXX XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXX XXXXXXXXXXXXXXXX
    XXXX X
		XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
	X
	XXXXXXXXXXXXXX X		
		XXXXXX XXXXXXXX
		XXXXXX XXXXXX
	X
	XXXXXXXXXXXXXX XXXXXXXXXXXXXX X
		XXXXXXXX XXXXX
		XXXXXXXXXXXXXX XXXX
		XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
		XXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXX XXXXXXXXXXXXX X
		XXXXXXXXXXXXXX XXXXX   
        XXXXXXXXX XXXXXXXXX
	X
	XXXXXXXXXXXXXX XX X
		XXXXXXXXXXX XXXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXX XXXX X XXXXXX
	X
	XXXXXXXXXXXXXX XXXXXX X
        XXXXXXXXX XXXXXXXXX
		XXXX XXXXX
		XXXXXX XXXXX
	X
	XXXXXXXXXXXXXX XXXXXXXXXXX X
		XXXXXX XXXXX
	X
	XXXXXXXXXXXXXX XXXXXXXXXXXXX X
		XXXXXXX XXXXX
		XXXXXXXXXXX XXXXXXX		
		XXXXXXXXXXXXXX XXXX
		XXXXXXXXXX XXXXX
		XXXXXXXX XXXX XXXX XXXXX
	X
	XXXXXXXXXXXXXX XXXXXXXXXXXXX X X
		XXXXXX XXXXX
	X		
	XXXXXXXXXXXXXX XXXXXXXXX X
		XXXXXX XXXXX
		XXXXXXX XXXXX
		XXXXXXX X XXXXX
		XXXXXXXXXXXXXX XXXX
		XXXXXXXX XX
		XXXXXXXXXXX XXXXXXX
		XXXXXXX XXX XXXXX XXXXXXXX
	X
	XXXXXXXXXXXXXX XXXXXXXXX X X
		XXXXXX XXXXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXX XXXXXXXXXXXXX
		XXXXXXXXXXX XXXXX
	X
    XXXXXXXXXXXXXX XXXX X
        XXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
		XXXXXXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXX XXX XXXXX
        XXXXXXXXXXXX XXXXXXX
		XXXXXXXXXX XXXXXX
        XXXXXXX XXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXX XXXX
		XXXXXXX X XXXX
		XXXXXXXX XXXX XXXXXXXXXXX
    X
	XXXXXXXXXXXXXX XXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
	XXXXXXXXXXXX X
		XXXXXXXX XXXXXXXXXXXXX
		XXXXXXX XXXXX XXXXX
	X
XXXXXXXX
XXXXXXX
XXXXXX
XXXX XXXX XXXXXXXXXXXXXXXXXXXX
	XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXX XXXXXXXXX
XXXXXX XXX

XXXX XXXXX XXXX XXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXX
					XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX				
				XXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX	
                    XX XXXXXXBBB BBBBBBBBBBBBBBX  XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXX
				XXXXX XXX XXXXXX XXXX XX XXXXXX XXXXX XXXXXXXX XXXX XXXXXXX XXXXXX XX XXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                         BBBBBBBBBB
                         XXXX XX XXXXXXBBB BBBBBBBBBBBBBBX  XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                         XX XXXXXXBBB BBBBBBBBBBBBBBX  XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
XXXXXX     
XXXXXXX
XXXXXXX 
XXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX

