# Generated by Django 3.0.6 on 2020-09-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='drawer_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='session_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
