# Generated by Django 3.0.6 on 2020-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_logs_productlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
