# Generated by Django 3.0.6 on 2020-09-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_product_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
