# Generated by Django 3.0.6 on 2020-10-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_backupcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuplogs',
            name='user',
        ),
        migrations.DeleteModel(
            name='BackupCategory',
        ),
        migrations.DeleteModel(
            name='BackupLogs',
        ),
    ]
