# Generated by Django 3.0.6 on 2020-10-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20201003_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='return_order',
            field=models.BooleanField(default=False),
        ),
    ]
